name: "SonarQube Scan"
description: "Führt SonarQube/Cloud Analyse via Maven aus"
inputs:
  java-version:
    default: "17"
  distribution:
    default: "temurin"
  sonar-host-url:
    description: "SonarQube Host URL"
    required: true
  extra-maven-args:
    description: "Zusätzliche Maven-Argumente"
    default: "-B -DskipTests=false"
runs:
  using: "composite"
  steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: ${{ inputs.distribution }}
        java-version: ${{ inputs.java-version }}
        cache: maven

    - name: SonarQube Scan (Maven)
      shell: bash
      env:
        SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
      run: |
        if [ -z "${SONAR_TOKEN}" ]; then
          echo "SONAR_TOKEN ist nicht gesetzt." >&2
          exit 1
        fi
        mvn ${{ inputs.extra-maven-args }} \
          verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.host.url="${{ inputs.sonar-host-url }}"
