name: ci

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & test
        run: mvn -B -DskipTests=false clean verify

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: quarkus-lib-example-jar
          path: |
            target/*.jar

      - name: Deploy to GitHub Packages
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        run: mvn -B -DskipTests=true deploy
